### ISSUE TITLE
Publish YARD doc to GitHub Pages

### ISSUE THREAD

**Issue by sue445** [yhara/simple_twitter#5]

**Comment by sue445** [comment]
@yhara I want to use GitHub Pages for gem reference. (There is also https://rubydoc.info/ but I don't like to use it as it is often heavy :sweat_smile:)

I have added a configuration to deploy to GitHub Pages with #13 , but deploy job failed. 😢 
https://github.com/yhara/simple_twitter/actions/runs/5566375694/jobs/10167431942

Could you please change the settings at https://github.com/yhara/simple_twitter/settings/pages as they probably need to be changed by the owner?

This is an example from my repository.

![image](https://github.com/yhara/simple_twitter/assets/608755/8480bbad-35d5-44be-b102-b52821e15104)

**Comment by yhara** [comment]
@sue445 Done!

**Comment by sue445** [comment]
@yhara thx!

https://github.com/yhara/simple_twitter/actions/runs/5566628950/jobs/10167885287 is passed and https://yhara.github.io/simple_twitter/ has been available! 🚀
